/**
 * Content registry and the builders that turn a language bundle into the
 * option lists the form components consume.
 *
 * The builders are the safety property of this module: every option list is
 * generated by walking `schema.ts` and looking the label up by value. A
 * language bundle therefore cannot change what is stored — only how it reads.
 */

import { CASES_PER_PARTICIPANT, en, type ContentBundle } from './en.ts';
import { es } from './es.ts';
import {
  CONFIDENCE_VALUES,
  PARTICIPANT_OPTION_VALUES,
  PARTICIPANT_QUESTION_ORDER,
  WINNER_VALUES,
  type ConfidenceValue,
  type ParticipantKey,
  type WinnerValue,
} from './schema.ts';
import type { Language } from '../i18n/language.ts';

export { CASES_PER_PARTICIPANT };
export type { ContentBundle };

/**
 * Research provenance, stored with every submission so any row in the database
 * can be traced to the exact protocol and consent text that produced it.
 *
 * `SURVEY_PROTOCOL_VERSION` changes when the participant's experience changes.
 * `CONSENT_VERSION` changes when the consent or instruction wording changes.
 * Neither changes for a translation: the same protocol and the same consent,
 * stated in another language, is still that protocol and that consent. The
 * language a participant read is a display concern and is deliberately not
 * recorded here.
 * `dataset_version` is NOT here — it is read from the loaded dataset.
 */
export const SURVEY_PROTOCOL_VERSION = 'final_feedback_v1';
export const CONSENT_VERSION = 'v2';

export const CONTENT: Record<Language, ContentBundle> = { en, es };

/** One selectable option: a stable machine value plus a display label. */
export interface QuestionOption {
  value: string;
  label: string;
}

export interface ParticipantQuestion {
  /** Key into ParticipantAnswers. */
  key: ParticipantKey;
  question: string;
  options: QuestionOption[];
}

/**
 * The five participant questions for one language, in schema order, with each
 * option's stored value taken from the schema and only its label localized.
 */
export function buildParticipantQuestions(
  content: ContentBundle
): ParticipantQuestion[] {
  return PARTICIPANT_QUESTION_ORDER.map((key) => ({
    key,
    question: content.participant.questions[key],
    // The index signature is per-question, so each list is narrowed to its own
    // value union before the lookup.
    options: (PARTICIPANT_OPTION_VALUES[key] as readonly string[]).map(
      (value) => ({
        value,
        label: (content.participant.options[key] as Record<string, string>)[
          value
        ],
      })
    ),
  }));
}

/** Blue/Red choices; values are the literal payload values. */
export function buildWinnerOptions(
  content: ContentBundle
): { value: WinnerValue; label: string }[] {
  return WINNER_VALUES.map((value) => ({
    value,
    label: content.survey.winnerLabels[value],
  }));
}

/** The 1–5 confidence scale; values are the literal payload values. */
export function buildConfidenceOptions(
  content: ContentBundle
): { value: ConfidenceValue; label: string }[] {
  return CONFIDENCE_VALUES.map((value) => ({
    value,
    label: content.survey.confidenceLabels[value],
  }));
}
