"""Initial schema: responses, answers, and the private case outcome key.

Revision ID: 0001
Revises:
Create Date: 2026-07-18

Written by hand rather than autogenerated so the CHECK constraints and their
names are explicit and reviewable. The allowed value lists are imported from
app.enums, which is also what the Pydantic request schemas validate against —
one source of truth for what may be stored.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.enums import (
    ANSWERS_PER_RESPONSE,
    CONFIDENCE_MAX,
    CONFIDENCE_MIN,
    CUTOFF_MINUTES,
    MAIN_ROLES,
    PLAYING_FREQUENCIES,
    RANKS,
    REGIONS,
    TEAMS,
    YEARS_PLAYING,
    sql_in_list,
)

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # The answer key is created first: survey_answers references it.
    op.create_table(
        "survey_case_outcomes",
        sa.Column("case_id", sa.Text(), nullable=False),
        sa.Column("match_group_id", sa.Text(), nullable=False),
        sa.Column("cutoff_minute", sa.SmallInteger(), nullable=False),
        sa.Column("dataset_version", sa.Text(), nullable=False),
        sa.Column("winning_team", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("case_id"),
        sa.UniqueConstraint(
            "match_group_id", "cutoff_minute", name="uq_outcome_group_cutoff"
        ),
        sa.CheckConstraint(
            f"cutoff_minute IN ({', '.join(str(c) for c in CUTOFF_MINUTES)})",
            name="ck_outcome_cutoff_minute",
        ),
        sa.CheckConstraint(
            f"winning_team IN ({sql_in_list(TEAMS)})", name="ck_outcome_winning_team"
        ),
    )
    op.create_index("ix_outcome_match_group", "survey_case_outcomes", ["match_group_id"])

    op.create_table(
        "survey_responses",
        sa.Column("response_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rank", sa.Text(), nullable=False),
        sa.Column("years_playing", sa.Text(), nullable=False),
        sa.Column("main_role", sa.Text(), nullable=False),
        sa.Column("playing_frequency", sa.Text(), nullable=False),
        sa.Column("region", sa.Text(), nullable=False),
        sa.Column("dataset_version", sa.Text(), nullable=False),
        sa.Column("survey_protocol_version", sa.Text(), nullable=False),
        sa.Column("consent_version", sa.Text(), nullable=False),
        sa.Column("consent_accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("survey_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("survey_finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("payload_fingerprint", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("response_id"),
        sa.CheckConstraint(f"rank IN ({sql_in_list(RANKS)})", name="ck_response_rank"),
        sa.CheckConstraint(
            f"years_playing IN ({sql_in_list(YEARS_PLAYING)})",
            name="ck_response_years_playing",
        ),
        sa.CheckConstraint(
            f"main_role IN ({sql_in_list(MAIN_ROLES)})", name="ck_response_main_role"
        ),
        sa.CheckConstraint(
            f"playing_frequency IN ({sql_in_list(PLAYING_FREQUENCIES)})",
            name="ck_response_playing_frequency",
        ),
        sa.CheckConstraint(
            f"region IN ({sql_in_list(REGIONS)})", name="ck_response_region"
        ),
        sa.CheckConstraint(
            "survey_finished_at >= survey_started_at", name="ck_response_time_order"
        ),
    )

    op.create_table(
        "survey_answers",
        sa.Column("response_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("question_order", sa.SmallInteger(), nullable=False),
        sa.Column("case_id", sa.Text(), nullable=False),
        sa.Column("predicted_winner", sa.Text(), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column("shown_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["response_id"], ["survey_responses.response_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["case_id"], ["survey_case_outcomes.case_id"]),
        sa.PrimaryKeyConstraint("response_id", "question_order"),
        sa.UniqueConstraint("response_id", "case_id", name="uq_answer_response_case"),
        sa.CheckConstraint(
            f"question_order BETWEEN 1 AND {ANSWERS_PER_RESPONSE}",
            name="ck_answer_question_order",
        ),
        sa.CheckConstraint(
            f"predicted_winner IN ({sql_in_list(TEAMS)})",
            name="ck_answer_predicted_winner",
        ),
        sa.CheckConstraint(
            f"confidence BETWEEN {CONFIDENCE_MIN} AND {CONFIDENCE_MAX}",
            name="ck_answer_confidence",
        ),
        sa.CheckConstraint("response_time_ms >= 0", name="ck_answer_response_time"),
    )
    op.create_index("ix_answer_case_id", "survey_answers", ["case_id"])


def downgrade() -> None:
    op.drop_index("ix_answer_case_id", table_name="survey_answers")
    op.drop_table("survey_answers")
    op.drop_table("survey_responses")
    op.drop_index("ix_outcome_match_group", table_name="survey_case_outcomes")
    op.drop_table("survey_case_outcomes")
