"""Database models.

Three tables, the smallest design that preserves the research data:

  survey_responses      one row per completed participant submission
  survey_answers        exactly ten rows per response
  survey_case_outcomes  the private answer key, imported once from upstream

Deliberately absent:
  - a users table (participation is anonymous; there is nothing to identify)
  - a matches table (match_group_id on the outcome row is enough for grouping)
  - a stored `correct` column. Correctness is derived by joining an answer to
    its outcome (`predicted_winner == winning_team`). Storing it would create a
    second source of truth for the paper's dependent variable, and at ten rows
    per participant there is no performance argument for denormalizing.

No IP address, user agent, device, or browser metadata is collected, matching
the privacy note in frontend/src/types/submission.ts.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from .types import GUID

from .enums import (
    ANSWERS_PER_RESPONSE,
    CONFIDENCE_MAX,
    CONFIDENCE_MIN,
    CUTOFF_MINUTES,
    MAIN_ROLES,
    PLAYING_FREQUENCIES,
    RANKS,
    REGIONS,
    TEAMS,
    YEARS_PLAYING,
    sql_in_list,
)


class Base(DeclarativeBase):
    pass


class SurveyResponse(Base):
    """One completed submission. `response_id` is generated by the browser so a
    retry after an uncertain network result reuses the same key (see the
    idempotency handling in app/main.py)."""

    __tablename__ = "survey_responses"

    response_id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True)

    # Participant profile. Explicit typed columns, not a JSON blob: these are
    # the paper's independent variables and the form is fixed, not dynamic.
    rank: Mapped[str] = mapped_column(Text, nullable=False)
    years_playing: Mapped[str] = mapped_column(Text, nullable=False)
    main_role: Mapped[str] = mapped_column(Text, nullable=False)
    playing_frequency: Mapped[str] = mapped_column(Text, nullable=False)
    region: Mapped[str] = mapped_column(Text, nullable=False)

    # Reproducibility: which dataset, protocol, and consent text produced this row.
    dataset_version: Mapped[str] = mapped_column(Text, nullable=False)
    survey_protocol_version: Mapped[str] = mapped_column(Text, nullable=False)
    consent_version: Mapped[str] = mapped_column(Text, nullable=False)

    consent_accepted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    survey_started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    survey_finished_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    submitted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # SHA-256 over the canonical submission content. Lets an exact retry be
    # distinguished from a different payload reusing the same response_id.
    payload_fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)

    answers: Mapped[list["SurveyAnswer"]] = relationship(
        back_populates="response",
        cascade="all, delete-orphan",
        order_by="SurveyAnswer.question_order",
    )

    __table_args__ = (
        CheckConstraint(f"rank IN ({sql_in_list(RANKS)})", name="ck_response_rank"),
        CheckConstraint(
            f"years_playing IN ({sql_in_list(YEARS_PLAYING)})",
            name="ck_response_years_playing",
        ),
        CheckConstraint(
            f"main_role IN ({sql_in_list(MAIN_ROLES)})", name="ck_response_main_role"
        ),
        CheckConstraint(
            f"playing_frequency IN ({sql_in_list(PLAYING_FREQUENCIES)})",
            name="ck_response_playing_frequency",
        ),
        CheckConstraint(
            f"region IN ({sql_in_list(REGIONS)})", name="ck_response_region"
        ),
        CheckConstraint(
            "survey_finished_at >= survey_started_at", name="ck_response_time_order"
        ),
    )


class SurveyAnswer(Base):
    """One prediction. Exactly ten rows exist per response; the API writes them
    in the same transaction as the parent row and never individually."""

    __tablename__ = "survey_answers"

    response_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("survey_responses.response_id", ondelete="CASCADE"),
        primary_key=True,
    )
    question_order: Mapped[int] = mapped_column(SmallInteger, primary_key=True)

    case_id: Mapped[str] = mapped_column(
        Text, ForeignKey("survey_case_outcomes.case_id"), nullable=False
    )
    predicted_winner: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[int] = mapped_column(SmallInteger, nullable=False)

    shown_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    answered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    response_time_ms: Mapped[int] = mapped_column(Integer, nullable=False)

    response: Mapped[SurveyResponse] = relationship(back_populates="answers")
    outcome: Mapped["SurveyCaseOutcome"] = relationship()

    __table_args__ = (
        UniqueConstraint("response_id", "case_id", name="uq_answer_response_case"),
        CheckConstraint(
            f"question_order BETWEEN 1 AND {ANSWERS_PER_RESPONSE}",
            name="ck_answer_question_order",
        ),
        CheckConstraint(
            f"predicted_winner IN ({sql_in_list(TEAMS)})",
            name="ck_answer_predicted_winner",
        ),
        CheckConstraint(
            f"confidence BETWEEN {CONFIDENCE_MIN} AND {CONFIDENCE_MAX}",
            name="ck_answer_confidence",
        ),
        CheckConstraint("response_time_ms >= 0", name="ck_answer_response_time"),
        Index("ix_answer_case_id", "case_id"),
    )


class SurveyCaseOutcome(Base):
    """The private answer key: which team actually won each published case.

    Written exactly once by scripts/import_case_outcomes.py and never by the
    API. This table - not the import file - is the runtime source of outcomes;
    the application must remain fully functional after the import artifact is
    deleted from disk.
    """

    __tablename__ = "survey_case_outcomes"

    case_id: Mapped[str] = mapped_column(Text, primary_key=True)
    match_group_id: Mapped[str] = mapped_column(Text, nullable=False)
    cutoff_minute: Mapped[int] = mapped_column(SmallInteger, nullable=False)
    dataset_version: Mapped[str] = mapped_column(Text, nullable=False)
    winning_team: Mapped[str] = mapped_column(Text, nullable=False)

    __table_args__ = (
        UniqueConstraint(
            "match_group_id", "cutoff_minute", name="uq_outcome_group_cutoff"
        ),
        CheckConstraint(
            f"cutoff_minute IN ({', '.join(str(c) for c in CUTOFF_MINUTES)})",
            name="ck_outcome_cutoff_minute",
        ),
        CheckConstraint(
            f"winning_team IN ({sql_in_list(TEAMS)})", name="ck_outcome_winning_team"
        ),
        Index("ix_outcome_match_group", "match_group_id"),
    )
